import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

const files = [
  ".env.test",
  ".env.production",
  ".prettierrc",
  ".prettierignore",
  "next.config.js",
  "tailwind.config.js",
  ".eslintrc.json",
  "components.json",
  "jest.config.js",
  "vitest.config.ts",
  "playwright.config.ts",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
  "CHANGELOG.md",
  "SECURITY.md",
  "LICENSE",
  "docs/API.md",
  "docs/DEPLOYMENT.md",
  "docs/MPESA_SETUP.md",
  "docs/KRA_INTEGRATION.md",
  "docs/ADMIN_GUIDE.md",
  "docs/USER_GUIDE.md",
  ".github/workflows/ci.yml",
  ".github/workflows/deploy-preview.yml",
  ".github/workflows/deploy-production.yml",
  ".github/ISSUE_TEMPLATE/bug_report.md",
  ".github/ISSUE_TEMPLATE/feature_request.md",
  ".github/PULL_REQUEST_TEMPLATE.md",
  ".vscode/settings.json",
  ".vscode/extensions.json",
  ".vscode/launch.json",
  "docker/.dockerignore",
  "docker/Dockerfile",
  "docker/Dockerfile.dev",
  "docker/docker-compose.yml",
  "scripts/create-admin.ts",
  "scripts/backup-db.ts",
  "scripts/restore-db.ts",
  "scripts/generate-types.ts",
  "src/middleware.ts",
  "src/styles/globals.css",
  "src/lib/db.ts",
  "src/lib/auth.ts",
  "src/lib/auth.config.ts",
  "src/lib/utils.ts",
  "src/lib/constants.ts",
  "src/lib/validations.ts",
  "src/lib/roles.ts",
  "src/lib/permissions.ts",
  "src/lib/mpesa/index.ts",
  "src/lib/mpesa/config.ts",
  "src/lib/mpesa/auth.ts",
  "src/lib/mpesa/stkpush.ts",
  "src/lib/mpesa/query.ts",
  "src/lib/mpesa/balance.ts",
  "src/lib/mpesa/register-url.ts",
  "src/lib/mpesa/types.ts",
  "src/lib/mpesa/errors.ts",
  "src/lib/mpesa/utils.ts",
  "src/lib/kra/index.ts",
  "src/lib/kra/calculator.ts",
  "src/lib/kra/excel-generator.ts",
  "src/lib/kra/pdf-generator.ts",
  "src/lib/kra/templates.ts",
  "src/lib/kra/validators.ts",
  "src/lib/sms/index.ts",
  "src/lib/sms/africastalking.ts",
  "src/lib/sms/templates.ts",
  "src/lib/sms/queue.ts",
  "src/lib/email/index.ts",
  "src/lib/email/resend.ts",
  "src/lib/email/templates.tsx",
  "src/lib/email/queue.ts",
  "src/components/ui/.gitkeep",
  "src/components/layout/.gitkeep",
  "src/components/shared/.gitkeep",
  "src/components/dashboard/.gitkeep",
  "src/components/admin-dashboard/.gitkeep",
  "src/components/payments/.gitkeep",
  "src/components/reports/.gitkeep",
  "src/components/charts/.gitkeep",
  "src/hooks/useAuth.ts",
  "src/hooks/useMpesaPayment.ts",
  "src/hooks/useLandlordStats.ts",
  "src/hooks/useAdminStats.ts",
  "src/contexts/AuthContext.tsx",
  "src/services/api-client.ts",
  "src/stores/auth.store.ts",
  "src/types/index.ts",
  "src/utils/formatters.ts",
  "src/config/site.ts",
  "tests/unit/lib/mpesa.test.ts",
  "tests/integration/api/properties.test.ts",
  "tests/e2e/landlord.spec.ts",
  "tests/setup/test-utils.tsx",
  "tests/setup/mocks/handlers.ts",
  "tests/setup/mocks/server.ts",
  "tests/setup/mocks/data.ts",
  "tests/setup/fixtures/landlord.json",
  "tests/setup/fixtures/property.json",
  "tests/setup/fixtures/tenant.json",
  "src/app/(auth)/login/page.tsx",
  "src/app/(auth)/register/page.tsx",
  "src/app/(auth)/verify-phone/page.tsx",
  "src/app/(dashboard)/dashboard/page.tsx",
  "src/app/(dashboard)/properties/page.tsx",
  "src/app/(dashboard)/tenants/page.tsx",
  "src/app/(dashboard)/payments/page.tsx",
  "src/app/(dashboard)/reports/page.tsx",
  "src/app/(dashboard)/settings/page.tsx",
  "src/app/(dashboard)/messages/page.tsx",
  "src/app/admin/dashboard/page.tsx",
  "src/app/admin/landlords/page.tsx",
  "src/app/admin/subscriptions/page.tsx",
  "src/app/admin/settings/page.tsx",
  "src/app/admin/audit-logs/page.tsx",
  "src/app/admin/support/page.tsx",
  "src/app/admin/analytics/page.tsx",
  "src/app/api/mpesa/stkpush/route.ts",
  "src/app/api/webhooks/mpesa-callback/route.ts",
];

const templateByExt = {
  ".ts": "export {};\n",
  ".tsx": 'export default function Placeholder() { return <div>Placeholder</div>; }\n',
  ".json": "{}\n",
  ".md": "# Placeholder\n",
  ".yml": "name: placeholder\n",
  ".yaml": "name: placeholder\n",
  ".css": "",
  ".prisma": "",
};

function contentFor(file) {
  const ext = path.extname(file);
  if (file.endsWith(".gitkeep")) return "";
  if (file.endsWith("LICENSE")) return "MIT License\n";
  if (file.endsWith(".env.test") || file.endsWith(".env.production")) return "";
  return templateByExt[ext] ?? "";
}

for (const relFile of files) {
  const abs = path.join(root, relFile);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  if (!fs.existsSync(abs)) {
    fs.writeFileSync(abs, contentFor(relFile), "utf8");
  }
}

console.log(`Scaffold complete. Ensured ${files.length} files.`);
